- hosts: localhost
  become: true
  tasks:
    - name: install the latest version of Apache and MariaDB
      dnf:
        name:
          - httpd 
          - php 
          - php-mysqlnd 
          - php-gd 
          - php-xml 
          - mariadb-server 
          - mariadb 
          - php-mbstring 
          - php-json
        state: latest

    - name: Start service httpd, if not started
      service:
        name: mariadb
        state: started

    - name: Ensure default user is present.
      mysql_user:
        name: wiki 
        host: 'localhost'
        password: wiki
        priv: '*.*:ALL,GRANT'
        state: present
      #when: mysql_user_name != mysql_root_username

    - name: Remove MySQL test database.
      mysql_db: "name='test' state=absent"

    - name: list DB
      shell: mysql -u root -proot -NBe "SHOW DATABASES like 'wikidatabase'"
      register: db_list

    - name: create DB
      shell: mysql -uroot -proot -NBe 'CREATE DATABASE wikidatabase'
      when: db_list.stdout == ""

    - name: grant permission
      shell: mysql -uroot -proot -NBe "GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'localhost'"

    - name: flush permission
      shell: mysql -uroot -proot -NBe "FLUSH PRIVILEGES"

    - name: Enable service httpd, and not touch the state
      service:
        name: httpd
        enabled: yes

    - name: Enable service httpd, and not touch the state
      service:
        name: mariadb
        enabled: yes

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz
        dest: /var/www/html
        owner: apache
        group: apache
        remote_src: yes

    - name: create sym link
      file:
        src: /var/www/html/mediawiki-1.34.2
        dest: /var/www/html/mediawiki
        owner: apache
        group: apache
        state: link

    - name: Change file ownership, group and permissions
      file:
        path: /var/www/html/mediawiki
        owner: apache
        group: apache

    - name: restart apache
      service:
        name: httpd
        state: restarted
