---
# tasks file for Configure_Application
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz
    dest: /var/www/html
    owner: apache
    group: apache
    remote_src: yes

- name: create sym link
  file:
    src: /var/www/html/mediawiki-1.34.2
    dest: /var/www/html/mediawiki
    owner: apache
    group: apache
    state: link

- name: Change file ownership, group and permissions
  file:
    path: /var/www/html/mediawiki
    owner: apache
    group: apache
