---
# tasks file for Pre_Req
- name: install the latest version of Apache and MariaDB
  dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - php-gd
      - php-xml
      - mariadb-server
      - mariadb
      - php-mbstring
      - php-json
    state: latest

- name: Start service httpd, if not started
  service:
    name: mariadb
    state: started
